stages:
  - build
  - test
  - deploy
  - migrations

variables:
  RUNNER_IMAGE: registry.gitlab.com/startfleet/gitlab-runner:v1.1

before_script:
  - mkdir ~/.kube/
  - echo $KUBECONFIG_PROD | base64 -d > ~/.kube/config

  ## Templates ##
.test-template: &test-template
  stage: test
  image: $RUNNER_IMAGE
  tags:
    - startfleet

.deploy-template: &deploy-template
  stage: deploy
  image: $RUNNER_IMAGE
  when: manual
  only:
    - master
    - tags
  tags:
    - startfleet
## End Templates ##

## Stages ##
# Test
test-keycloak:
  <<: *test-template
  script:
    - kubectl apply -f Kubernetes/backend/keycloak --dry-run=true
test-hasura:
  <<: *test-template
  script:
    - kubectl apply -f Kubernetes/backend/hasura --dry-run=true
test-armadacar:
  <<: *test-template
  script:
    - kubectl apply -f Kubernetes/frontend/armadacar --dry-run=true

# Deploy
deploy-hasura:
  <<: *deploy-template
  script:
    - kubectl apply -f Kubernetes/backend/hasura

deploy-armadacar:
  <<: *deploy-template
  script:
    - kubectl apply -f Kubernetes/frontend/armadacar

deploy-keycloak:
  <<: *deploy-template
  script:
    # build and deploy keycloak app
    - kubectl apply -f Kubernetes/backend/keycloak

hasura-migrations:
  stage: migrations
  image: $RUNNER_IMAGE
  when: manual
  only:
    - master
    - tags
  tags:
    - startfleet
  script:
    - hasura migrate apply --endpoint https://hasura.startfleet.ovh --admin-secret $HASURA_ADMIN_SECRET --project hasura-migration