stages:
  - build
  - test
  - deploy

variables:
  RUNNER_IMAGE: registry.gitlab.com/startfleet/gitlab-runner:v1.1

before_script:
  - mkdir ~/.kube/
  - echo $KUBECONFIG_PROD | base64 -d > ~/.kube/config

  ## Templates ##
.test-template: &test-template
  stage: test
  image: $RUNNER_IMAGE
  tags:
    - startfleet

.deploy-template: &deploy-template
  stage: deploy
  image: $RUNNER_IMAGE
  when: manual
  only:
    - master
    - tags
  tags:
    - startfleet
## End Templates ##

## Stages ##
# Test
test-keycloak:
  <<: *test-template
  script:
    - kubectl apply -f Kubernetes/backend/keycloak --dry-run=true
test-hasura:
  <<: *test-template
  script:
    - kubectl apply -f Kubernetes/backend/hasura/hasura-app --dry-run=true
test-armadacar:
  <<: *test-template
  script:
    - kubectl apply -f Kubernetes/frontend/armadacar --dry-run=true

# Deploy
deploy-hasura:
  <<: *deploy-template
  script:
    # building the deployment with substrings 
    - envsubst < Kubernetes/backend/hasura/hasura-app/hasura-deployment.yml > Hasura-Deployment.yml
    - kubectl -n hasura apply -f Hasura-Deployment.yml
    # building hasura service
    - kubectl -n hasura apply -f Kubernetes/backend/hasura/hasura-app/hasura-service.yml
    # building hasura ingress
    - kubectl -n hasura apply -f Kubernetes/backend/hasura/hasura-app/hasura-ingress.yml

deploy-armadacar:
  <<: *deploy-template
  script:
    - kubectl -n armadacar apply -f Kubernetes/frontend/armadacar/deployment.yml
    # Création du service armadacar
    - kubectl -n armadacar apply -f Kubernetes/frontend/armadacar/service.yml
    # Exposition de l'app via un ingress kubernetes
    - kubectl -n armadacar apply -f Kubernetes/frontend/armadacar/ingress.yml

deploy-keycloak:
  <<: *deploy-template
  script:
    # build and deploy keycloak app
    - kubectl apply -f Kubernetes/backend/keycloak

deploy-migrations:
  <<: *deploy-template
  script:
    - hasura migrate apply --endpoint https://hasura.startfleet.ovh --admin-secret $HASURA_ADMIN_SECRET --project hasura-migration