stages:
  - build
  - test
  - deploy

variables:
  PROD_KUBECONFIG: prod-kubeconfig.yml
  RUNNER_IMAGE: registry.gitlab.com/startfleet/gitlab-runner:v1.1

## Templates ##
.test-template: &test-template
  stage: test
  image: $RUNNER_IMAGE
  tags:
    - startfleet

.deploy-template: &deploy-template
  stage: deploy
  image: $RUNNER_IMAGE
  when: manual
  only:
    - master
    - tags
  tags:
    - startfleet
## End Templates ##

## Stages ##
# Build
kubeconfig:
  stage: build
  script:
    - echo $KUBECONFIG | base64 -d | cat > $PROD_KUBECONFIG
  artifacts:
    paths:
    - $PROD_KUBECONFIG
  tags:
    - startfleet

test-services:
  <<: *test-template
  script:
    - export KUBECONFIG=$PROD_KUBECONFIG
    - kubectl apply -f Kubernetes/backend/hasura/hasura-app/hasura-service.yml --dry-run=true
    - kubectl apply -f Kubernetes/frontend/armadacar/service.yml --dry-run=true

test-deployments:
  <<: *test-template
  script:
    - export KUBECONFIG=$PROD_KUBECONFIG
    - kubectl apply -f Kubernetes/backend/hasura/hasura-app/hasura-deployment.yml --dry-run=true
    - kubectl apply -f Kubernetes/frontend/armadacar/deployment.yml --dry-run=true

test-ingress:
  <<: *test-template
  script:
    - export KUBECONFIG=$PROD_KUBECONFIG
    - kubectl apply -f Kubernetes/frontend/armadacar/ingress.yml --dry-run=true

# Deploy
deploy-hasura:
  <<: *deploy-template
  script:
    - export KUBECONFIG=$PROD_KUBECONFIG
    # building the deployment with substrings 
    - envsubst < Kubernetes/backend/hasura/hasura-app/hasura-deployment.yml > Hasura-Deployment.yml
    - kubectl -n hasura apply -f Hasura-Deployment.yml
    # building hasura service
    - kubectl -n hasura apply -f Kubernetes/backend/hasura/hasura-app/hasura-service.yml
    # building hasura ingress
    - kubectl -n hasura apply -f Kubernetes/backend/hasura/hasura-app/hasura-ingress.yml

deploy-armadacar:
  <<: *deploy-template
  script:
    - export KUBECONFIG=$PROD_KUBECONFIG
    - kubectl -n armadacar apply -f Kubernetes/frontend/armadacar/deployment.yml
    # Création du service armadacar
    - kubectl -n armadacar apply -f Kubernetes/frontend/armadacar/service.yml
    # Exposition de l'app via un ingress kubernetes
    - kubectl -n armadacar apply -f Kubernetes/frontend/armadacar/ingress.yml

deploy-migrations:
  <<: *deploy-template
  script:
    - cd hasura-migration
    - hasura migrate apply --endpoint https://hasura.startfleet.ovh --admin-secret $HASURA_ADMIN_SECRET