version: '3.6'
services:
# Service Postgres for Hasura app
  hasura-postgres:
    image: postgres:11-alpine
    restart: always
    volumes:
    - db_hasura_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: hasura_user
      POSTGRES_PASSWORD: hasura_password
      POSTGRES_DB: hasura_db
# Service for Hasura app
  graphql-engine:
    image: hasura/graphql-engine:v1.1.1
    ports:
    - "8080:8080"
    depends_on:
    - hasura-postgres
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://hasura_user:hasura_password@hasura-postgres:5432/hasura_db
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_AUTH_HOOK: http://auth-hasura:3000
      HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey
# Service for Armadacar app
  armadacar-front:
    image: registry.gitlab.com/startfleet/armadacar-front:v0.5
    restart: always
    ports:
      - "8081:80"
# Service for Hasura auth
  auth-hasura:
    image: httpsomkar/keycloak-hasura-connector:latest
    depends_on:
    - graphql-engine
    restart:
      always
    environment:
      KEYCLOAK_CLIENT_ID: hasura-keycloak-connector
      KEYCLOAK_SERVER_URL: "https://keycloak.startfleet.ovh/auth"
      KEYCLOAK_SECRET: "b144171a-aef4-42c2-a47e-ea4128e8a1e6"
      KEYCLOAK_REALM: local
      USER_ID_FIELD: "sub"
      KEYCLOAK_DEBUG: "true"
      ANONYMOUS_ROLE: "anonymous"
volumes:
  db_hasura_data:

