apiVersion: apps/v1
kind: Deployment
metadata:
  name: hasura-deployment
  namespace: hasura
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hasura
      component: pod
  template:
    metadata:
      labels:
        app: hasura
        component: pod
    spec:
      affinity:
        # tell hasura pods to never deploy on the same node
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - hasura
            topologyKey: "kubernetes.io/hostname"
      containers:
      - image: hasura/graphql-engine:v1.1.1
        imagePullPolicy: IfNotPresent
        name: hasura
        env:
        - name: HASURA_GRAPHQL_DATABASE_URL
          value: postgres://$HUSER:$HPWD@bdd.startfleet.ovh:43401/apps
        - name: HASURA_GRAPHQL_ENABLE_CONSOLE
          value: "false"
        - name: HASURA_GRAPHQL_ADMIN_SECRET
          value: $HASURA_ADMIN_SECRET
        ports:
        - containerPort: 8080