apiVersion: apps/v1
kind: Deployment
metadata:
  name: hasura-deployment
  namespace: hasura
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hasura
      component: pod
  template:
    metadata:
      labels:
        app: hasura
        component: pod
    spec:
      containers:
      - image: hasura/graphql-engine:v1.0.0
        imagePullPolicy: IfNotPresent
        name: hasura
        env:
        - name: HASURA_GRAPHQL_DATABASE_URL
          value: postgres://$HUSER:$HPWD@bdd.bdd-service:43401/apps
        - name: HASURA_GRAPHQL_ENABLE_CONSOLE
          value: "false"
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}