apiVersion: apps/v1
kind: Deployment
metadata:
  name: hasura-deployment
  namespace: hasura
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hasura
      component: pod
  template:
    metadata:
      labels:
        app: hasura
        component: pod
    spec:
      affinity:
        # tell hasura pods to never deploy on the same node
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - hasura
            topologyKey: "kubernetes.io/hostname"
      containers:
      # hasura app image
      - image: hasura/graphql-engine:v1.1.1
        imagePullPolicy: IfNotPresent
        name: hasura-app
        envFrom:
        - secretRef:
            name: hasura-app-secret
        - configMapRef:
            name: hasura-app-configmap
        ports:
          - containerPort: 8080
      # connector image
      - image: httpsomkar/keycloak-hasura-connector:latest
        imagePullPolicy: IfNotPresent
        name: hasura-connector
        envFrom:
        - secretRef:
            name: hasura-connector-secret
        - configMapRef:
            name: hasura-connector-configmap
        ports:
          - containerPort: 3000